In [1]:
import numpy as np 

numbers = np.array([2, 3, 5, 7, 11])

In [3]:
type(numbers)

numbers

array([ 2,  3,  5,  7, 11])

In [4]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
integers = np.array([[1, 2, 3], [4, 5, 6]])

integers

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [8]:
floats.ndim

1

In [9]:
integers.ndim

2

In [10]:
integers.size

6

In [11]:
integers.itemsize

8

In [12]:
for i in integers.flat:
    print(i, end =' ')

1 2 3 4 5 6 

In [13]:
import numpy as np 

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones((2, 4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
np.full((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [16]:
import numpy as np 

np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [18]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [19]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [21]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]],
      shape=(4, 25000))

In [22]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]],
      shape=(100, 1000))

In [23]:
import random 

%timeit rolls_list = \
    [random.randrange(1, 7) for i in range(0, 6_000_000)]

1.24 s ± 7.78 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [25]:
import numpy as np 

%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

38.8 ms ± 1.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [26]:
import numpy as np 

numbers = np.arange(1, 6)

numbers

array([1, 2, 3, 4, 5])

In [27]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [28]:
numbers ** 3

array([  1,   8,  27,  64, 125])

In [29]:
numbers

array([1, 2, 3, 4, 5])

In [30]:
numbers += 10

numbers

array([11, 12, 13, 14, 15])

In [32]:
numbers2 = np.linspace(1.1, 5.5, 5)

numbers

numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [34]:
numbers

numbers >= 13

array([False, False,  True,  True,  True])

In [35]:
numbers2 == numbers

array([False, False, False, False, False])

In [36]:
numbers == numbers

array([ True,  True,  True,  True,  True])

In [38]:
#numpy calculation method
import numpy as np 

grades = np.array([[87, 96, 70], [100, 87, 90],
                  [94, 77, 90], [100, 81, 82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [39]:
grades.sum()

np.int64(1054)

In [40]:
grades.min()

np.int64(70)

In [41]:
grades.max()

np.int64(100)

In [42]:
grades.mean()

np.float64(87.83333333333333)

In [43]:
grades.std()

np.float64(8.792357792739987)

In [44]:
grades.var()

np.float64(77.30555555555556)

In [46]:
#calculations by row or column
grades.mean(axis = 1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [47]:
grades.mean(axis = 0)

array([95.25, 85.25, 83.  ])

In [48]:
numbers = np.array([1, 4, 9, 16, 25, 36])

np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [49]:
numbers2 = np.arange(1, 7) * 10

numbers2

array([10, 20, 30, 40, 50, 60])

In [50]:
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

In [51]:
np.multiply(numbers2, 5)

array([ 50, 100, 150, 200, 250, 300])

In [52]:
numbers3 = numbers2.reshape(2, 3)
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [54]:
numbers4 = np.array([2, 4, 6])

np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

In [55]:
#indexing and slicing

import numpy as np 

grades = np.array([[87, 96, 70], [100, 87, 90],
                  [94, 77, 90], [100, 81, 82]])

grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [56]:
grades[0, 1] # row 0 column 1

np.int64(96)

In [57]:
#subset of two dimensional array 
grades[1]

array([100,  87,  90])

In [58]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [59]:
grades[[1, 3]]

array([[100,  87,  90],
       [100,  81,  82]])

In [60]:
#subsetting a two-dimensional array
grades[:, 0]

array([ 87, 100,  94, 100])

In [61]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [62]:
grades[:, [0, 2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

In [90]:
#shallow copies
import numpy as np 

numbers = np.arange(1, 6)

numbers

array([1, 2, 3, 4, 5])

In [81]:
numbers2 = numbers.view()

numbers2

array([1, 2, 3, 4, 5])

In [82]:
id(numbers)

1890809034000

In [83]:
id(numbers2)

1890809035824

In [84]:
numbers[1] *= 10

numbers2

array([ 1, 20,  3,  4,  5])

In [85]:
numbers

array([ 1, 20,  3,  4,  5])

In [86]:
numbers2[1] /= 10

numbers

array([1, 2, 3, 4, 5])

In [87]:
numbers2

array([1, 2, 3, 4, 5])

In [91]:
numbers2 = numbers[0:3]

numbers2

array([1, 2, 3])

In [ ]:
numbers2[3]

In [94]:
#Deep copies

import numpy as np 

numbers = np.arange(1, 6)

numbers

array([1, 2, 3, 4, 5])

In [95]:
numbers2 = numbers.copy()

numbers2

array([1, 2, 3, 4, 5])

In [96]:
numbers[1] *= 10

numbers

array([ 1, 20,  3,  4,  5])

In [97]:
numbers2

array([1, 2, 3, 4, 5])

In [99]:
#reshaping and transposing
import numpy as np 

grades = np.array([[87, 96, 70], [100, 87, 90]])

grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [100]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [101]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [102]:
#resizing modify's the original array's shape 
grades.resize(1, 6)

In [103]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

In [105]:
grades = np.array([[87, 96, 70],
                   [100, 87, 90]])


grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [106]:
flattened = grades.flatten()

flattened

array([ 87,  96,  70, 100,  87,  90])

In [107]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [109]:
flattened[0] = 100

flattened

array([100,  96,  70, 100,  87,  90])

In [110]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [111]:
raveled = grades.ravel()

raveled

array([ 87,  96,  70, 100,  87,  90])

In [112]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [113]:
raveled[0] = 100

raveled

array([100,  96,  70, 100,  87,  90])

In [114]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [115]:
#transposing 
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [116]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [118]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])
grades2

array([[ 94,  77,  90],
       [100,  81,  82]])

In [119]:
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [120]:
np.vstack((grades, grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [121]:
#using panel data (pandas)
import pandas as pd 

grades = pd.Series([87, 100, 94])

In [122]:
grades

0     87
1    100
2     94
dtype: int64

In [123]:
pd.Series(98.6, range(3))

0    98.6
1    98.6
2    98.6
dtype: float64

In [124]:
grades[0]

np.int64(87)

In [125]:
grades.count()

np.int64(3)

In [126]:
grades.mean()

np.float64(93.66666666666667)

In [127]:
grades.min()

np.int64(87)

In [128]:
grades.max()

np.int64(100)

In [129]:
grades.describe()

count      3.000000
mean      93.666667
std        6.506407
min       87.000000
25%       90.500000
50%       94.000000
75%       97.000000
max      100.000000
dtype: float64

In [131]:
#creating customer series
grades = pd.Series([87, 100, 94], index=['Wally', 'Eva', 'Same'])
grades

Wally     87
Eva      100
Same      94
dtype: int64

In [133]:
grades = pd.Series({
    'Wally':87,
    'Eva': 100,
    'Sam':94
})

grades

Wally     87
Eva      100
Sam       94
dtype: int64

In [134]:
grades['Eva']

np.int64(100)

In [135]:
grades.Wally

np.int64(87)

In [136]:
grades.values

array([ 87, 100,  94])

In [4]:
import pandas as pd

hardware = pd.Series(['Hammer', 'Sam', 'Wrench'])

In [5]:
#using str attribute to call string methods on series
hardware.str.contains('a')

0     True
1     True
2    False
dtype: bool

In [6]:
hardware.str.upper()

0    HAMMER
1       SAM
2    WRENCH
dtype: object

In [8]:
#using dataframes 
import pandas as pd 

grades_dict = {
    'Wally': [87, 96, 70],
    'Eva': [100, 87, 90],
    'Sam': [94, 77, 90],
    'Katie': [100, 81, 82],
    'Bob': [83, 65, 85]
}

grades = pd.DataFrame(grades_dict)

grades

Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85

In [9]:
grades.index = ['Test1', 'Test2', 'Test3']

grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [10]:
#accessing a dataframe 
grades['Eva']

Test1    100
Test2     87
Test3     90
Name: Eva, dtype: int64

In [11]:
grades.Sam

Test1    94
Test2    77
Test3    90
Name: Sam, dtype: int64

In [14]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [12]:
grades.loc['Test1']

Wally     87
Eva      100
Sam       94
Katie    100
Bob       83
Name: Test1, dtype: int64

In [13]:
grades.iloc[1]

Wally    96
Eva      87
Sam      77
Katie    81
Bob      65
Name: Test2, dtype: int64

In [15]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [16]:
grades.loc['Test1':'Test3']

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [17]:
grades.iloc[0:2]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65

In [18]:
grades.iloc[[0,2]]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [19]:
grades.loc[['Test1', 'Test3']]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [20]:
#doing selection based on rows and columns 

grades.loc['Test1':'Test2',['Eva','Katie']]

Eva  Katie
Test1  100    100
Test2   87     81

In [21]:
grades.iloc[[0,2], 0:3]

Wally  Eva  Sam
Test1     87  100   94
Test3     70   90   90

In [22]:
#Boolean indexing 

grades[grades >= 90]

Wally    Eva   Sam  Katie  Bob
Test1    NaN  100.0  94.0  100.0  NaN
Test2   96.0    NaN   NaN    NaN  NaN
Test3    NaN   90.0  90.0    NaN  NaN

In [23]:
grades[(grades >=80) & (grades < 90)]

Wally   Eva  Sam  Katie   Bob
Test1   87.0   NaN  NaN    NaN  83.0
Test2    NaN  87.0  NaN   81.0   NaN
Test3    NaN   NaN  NaN   82.0  85.0

In [24]:
grades.at['Test2', 'Eva']

np.int64(87)

In [26]:
grades 

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [25]:
grades.iat[2, 0]

np.int64(70)

In [27]:
#you can use iat and at to also change the values of the dataframe
grades.at['Test2','Eva'] = 100

grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96  100   77     81   65
Test3     70   90   90     82   85

In [29]:
grades.iat[1,1] = 87

grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   87     81   65
Test3     70   90   90     82   85

In [30]:
#Descriptive statistics
grades.describe()

Wally         Eva        Sam       Katie        Bob
count   3.000000    3.000000   3.000000    3.000000   3.000000
mean   84.333333   92.333333  90.333333   87.666667  77.666667
std    13.203535    6.806859   3.511885   10.692677  11.015141
min    70.000000   87.000000  87.000000   81.000000  65.000000
25%    78.500000   88.500000  88.500000   81.500000  74.000000
50%    87.000000   90.000000  90.000000   82.000000  83.000000
75%    91.500000   95.000000  92.000000   91.000000  84.000000
max    96.000000  100.000000  94.000000  100.000000  85.000000

In [32]:
#we can set the precision option
pd.set_option('display.precision', 2)

In [33]:
grades.describe()

Wally     Eva    Sam   Katie    Bob
count   3.00    3.00   3.00    3.00   3.00
mean   84.33   92.33  90.33   87.67  77.67
std    13.20    6.81   3.51   10.69  11.02
min    70.00   87.00  87.00   81.00  65.00
25%    78.50   88.50  88.50   81.50  74.00
50%    87.00   90.00  90.00   82.00  83.00
75%    91.50   95.00  92.00   91.00  84.00
max    96.00  100.00  94.00  100.00  85.00

In [ ]:
#determining the mean of the grades
grades.mean()

Wally    84.33
Eva      92.33
Sam      90.33
Katie    87.67
Bob      77.67
dtype: float64

In [35]:
#transposing the dataframe 
grades.T

Test1  Test2  Test3
Wally     87     96     70
Eva      100     87     90
Sam       94     87     90
Katie    100     81     82
Bob       83     65     85

In [36]:
#if we want the summary statistics by tests

grades.T.describe()

Test1  Test2  Test3
count    5.00    5.0   5.00
mean    92.80   83.2  83.40
std      7.66   11.5   8.23
min     83.00   65.0  70.00
25%     87.00   81.0  82.00
50%     94.00   87.0  85.00
75%    100.00   87.0  90.00
max    100.00   96.0  90.00

In [37]:
#determining the mean of the tests
grades.T.mean()

Test1    92.8
Test2    83.2
Test3    83.4
dtype: float64

In [38]:
#Sorting the dataframe by rows by their indices
grades.sort_index(ascending=False)

Wally  Eva  Sam  Katie  Bob
Test3     70   90   90     82   85
Test2     96   87   87     81   65
Test1     87  100   94    100   83

In [39]:
#sorting the column names 
grades.sort_index(axis=1)

Bob  Eva  Katie  Sam  Wally
Test1   83  100    100   94     87
Test2   65   87     81   87     96
Test3   85   90     82   90     70

In [40]:
#Sort by column values 
grades.sort_values(by='Test1', axis=1, ascending=False)

Eva  Katie  Sam  Wally  Bob
Test1  100    100   94     87   83
Test2   87     81   87     96   65
Test3   90     82   90     70   85

In [41]:
#when you do the transpose the column names become the index. Hence no need to specify axis = 1
grades.T.sort_values(by='Test1', ascending=False)

Test1  Test2  Test3
Eva      100     87     90
Katie    100     81     82
Sam       94     87     90
Wally     87     96     70
Bob       83     65     85

In [42]:
#we can restrict to the column we are interested in 
grades.loc['Test1'].sort_values(ascending=False)

Eva      100
Katie    100
Sam       94
Wally     87
Bob       83
Name: Test1, dtype: int64